# Base configuration for competitor clustering pipeline

# Model settings
model_name: "sentence-transformers/all-mpnet-base-v2"
k: 20
tau: 0.55
alpha: 0.6
seed: 42

# Data paths
input: "data/processed/edsl_survey.csv"
output_dir: "data/processed/competitor_clustering"
